### ISSUE TITLE
Vim-Airline Not Rendering

### ISSUE THREAD

**Issue by pineapplegiant** [koirand/tokyo-metro.vim#5]
Environment:
- OS: **OSX 10.14.1**
- Vim (`:version`) **Nvim 0.3.1**
- Terminal: **iTerm2**

<img width="1424" alt="screen shot 2018-11-14 at 1 25 04 pm" src="https://user-images.githubusercontent.com/32819563/48503679-bfcffd80-e810-11e8-83dc-eca506c78ee9.png">

I'm having trouble getting vim-airline to work.

And however you compiled it, the vim-airline file has not been appropriately populated. I did a little digging and I found it's because this matrix does not have the appropriate colors added to the `autoload/airline/themes/tokyo-metro.vim`file, you can see it when compared to the original Iceberg.vim. I spent all day yesterday trying to figure out how Iceberg.vim works with pgmnt.vim and do not understand how to use it so I apologize I couldn't create a pull request with a fix for this. 

Such a beautiful theme by the way :) . I'm trying to figure out how it works myself because I want to make a similar theme.

**Comment by pineapplegiant** [comment]
OKAY SO, I'm an idiot
<img width="1438" alt="screen shot 2018-11-14 at 5 32 31 pm" src="https://user-images.githubusercontent.com/32819563/48517381-20bcfd00-e834-11e8-8515-8bfacb656242.png">

I was trying to compile it and it erased the color matrix. It works now!

However, you need to change the last line of code to make vim-airline recognize the theme. Right now it's:
`let g:airline#themes#iceberg#palette = s:build_palette()`

When it should be:
`let g:airline#themes#tokyometro#palette = s:build_palette()`

And I think you need to change the name of the file to the same name! I guess you can close this and make it a pull request instead? :)
LOL 👍

**Comment by koirand** [comment]
@pineapplegiant 
Thank you for debugging. 😸
